// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArL3nnDG3ywSXX6vtMd3reCW5I3-XFitg',
    appId: '1:1084091221851:web:8ade7d0cf5f94cfaf03c7e',
    messagingSenderId: '1084091221851',
    projectId: 'hamrobike-e51e7',
    authDomain: 'hamrobike-e51e7.firebaseapp.com',
    storageBucket: 'hamrobike-e51e7.firebasestorage.app',
    measurementId: 'G-942GLTSMCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCovFPAs9RQ1SmRYgyGQDy8vtdnpiXsFYs',
    appId: '1:1084091221851:android:9bffb05d8cea77b6f03c7e',
    messagingSenderId: '1084091221851',
    projectId: 'hamrobike-e51e7',
    storageBucket: 'hamrobike-e51e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdoYw7b0TsGvJzQ8ig-pKwscuTUztz83s',
    appId: '1:1084091221851:ios:3accef81a1fd0e3df03c7e',
    messagingSenderId: '1084091221851',
    projectId: 'hamrobike-e51e7',
    storageBucket: 'hamrobike-e51e7.firebasestorage.app',
    iosBundleId: 'com.example.hamroBike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdoYw7b0TsGvJzQ8ig-pKwscuTUztz83s',
    appId: '1:1084091221851:ios:3accef81a1fd0e3df03c7e',
    messagingSenderId: '1084091221851',
    projectId: 'hamrobike-e51e7',
    storageBucket: 'hamrobike-e51e7.firebasestorage.app',
    iosBundleId: 'com.example.hamroBike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArL3nnDG3ywSXX6vtMd3reCW5I3-XFitg',
    appId: '1:1084091221851:web:980844613ec2ccb4f03c7e',
    messagingSenderId: '1084091221851',
    projectId: 'hamrobike-e51e7',
    authDomain: 'hamrobike-e51e7.firebaseapp.com',
    storageBucket: 'hamrobike-e51e7.firebasestorage.app',
    measurementId: 'G-HQ6G0903BB',
  );
}
